from census_parse.pid_file import *

from pathlib import Path

THIS_DIR = Path(__file__).parent

pid_test_list = [
    "010000226085ALABAMA                                                                                                   490318520             093020",
    "011003160514BALDWIN COUNTY                                                  Baldwin                            99003   22323420             093020",
]

alabama_state_dict = {
    'ID': '010000226085',
    'Name': 'ALABAMA',
    'County': '',
    'FIPS Place Code': '',
    'Population': 4903185,
    'Population Year': '20',
    'Enrollment': 0,
    'Enrollment Year': '',
    'School Level Code': '',
    'Funciton Code for Special Districts': '',
    'Fiscal Year Ending': '0930',
    'Survey Year': '20'
}
baldwin_county_dict = {
    'ID': '011003160514',
    'Name': 'BALDWIN COUNTY',
    'County': 'Baldwin',
    'FIPS Place Code': '99003',
    'Population': 223234,
    'Population Year': '20',
    'Enrollment': 0,
    'Enrollment Year': '',
    'School Level Code': '',
    'Funciton Code for Special Districts': '',
    'Fiscal Year Ending': '0930',
    'Survey Year': '20'
}

pid_list_dict = {
    alabama_state_dict['ID']: alabama_state_dict,
    baldwin_county_dict['ID']: baldwin_county_dict
}

sampled_census_dict = {
    '010000226085': {'County': '',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0930',
                    'Funciton Code for Special Districts': '',
                    'ID': '010000226085',
                    'Name': 'ALABAMA',
                    'Population': 4903185,
                    'Population Year': '20',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '064067225491': {'County': 'Sacramento',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '',
                    'Funciton Code for Special Districts': '41',
                    'ID': '064067225491',
                    'Name': 'CALIFORNIA ENTERPRISE DEVELOPMENT AUTHORITY',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '085095116045': {'County': 'Phillips',
                    'Enrollment': 0,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '085095116045',
                    'Name': 'NORTHEAST BOCES',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '07',
                    'Survey Year': '20'},
    '171113189911': {'County': 'McLean',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '99113',
                    'Fiscal Year Ending': '1231',
                    'Funciton Code for Special Districts': '',
                    'ID': '171113189911',
                    'Name': 'MCLEAN COUNTY',
                    'Population': 171517,
                    'Population Year': '20',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '185055116448': {'County': 'Greene',
                    'Enrollment': 718,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '185055116448',
                    'Name': 'SHAKAMAK METROPOLITAN SCHOOL DISTRICT',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '03',
                    'Survey Year': '20'},
    '215023210367': {'County': 'Bracken',
                    'Enrollment': 299,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '215023210367',
                    'Name': 'AUGUSTA INDEP SCH DIST',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '03',
                    'Survey Year': '20'},
    '265099179917': {'County': 'Macomb',
                    'Enrollment': 26632,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '265099179917',
                    'Name': 'UTICA COMM SCH DIST',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '03',
                    'Survey Year': '20'},
    '295033202088': {'County': 'Carroll',
                    'Enrollment': 177,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '295033202088',
                    'Name': 'NORBORNE SCH DIST R 8',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '03',
                    'Survey Year': '20'},
    '334001186523': {'County': 'Belknap',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0331',
                    'Funciton Code for Special Districts': '50',
                    'ID': '334001186523',
                    'Name': 'LACONIA HOUSING AND REDEVELOPMENT AUTHORITY',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '365059181567': {'County': 'Nassau',
                    'Enrollment': 1475,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '365059181567',
                    'Name': 'VALLEY STREAM UNION FREE SCH DIST 30',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '01',
                    'Survey Year': '20'},
    '395049118093': {'County': 'Franklin',
                    'Enrollment': 16519,
                    'Enrollment Year': '22',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '395049118093',
                    'Name': 'HILLIARD CITY SCHOOL DIST',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '03',
                    'Survey Year': '20'},
    '422013173825': {'County': 'Blair',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '02184',
                    'Fiscal Year Ending': '1231',
                    'Funciton Code for Special Districts': '',
                    'ID': '422013173825',
                    'Name': 'ALTOONA CITY',
                    'Population': 43364,
                    'Population Year': '20',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '474005156838': {'County': 'Benton',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0331',
                    'Funciton Code for Special Districts': '93',
                    'ID': '474005156838',
                    'Name': 'WEST TENNESSEE PUBLIC UTILITY DISTRICT',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '492039194158': {'County': 'Sanpete',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '53010',
                    'Fiscal Year Ending': '0630',
                    'Funciton Code for Special Districts': '',
                    'ID': '492039194158',
                    'Name': 'MOUNT PLEASANT CITY',
                    'Population': 3530,
                    'Population Year': '20',
                    'School Level Code': '',
                    'Survey Year': '20'},
    '554133136925': {'County': 'Waukesha',
                    'Enrollment': 0,
                    'Enrollment Year': '',
                    'FIPS Place Code': '',
                    'Fiscal Year Ending': '0930',
                    'Funciton Code for Special Districts': '50',
                    'ID': '554133136925',
                    'Name': 'WAUKESHA CITY-COUNTY HOUSING AUTHORITY',
                    'Population': 0,
                    'Population Year': '  ',
                    'School Level Code': '',
                    'Survey Year': '20'}
}

def test_parse_census_place_id_file():
    print(__file__)
    print(dir(THIS_DIR))
    pid_dict = parse_census_place_id_file(str(THIS_DIR) + '/test_data/sampled_census_pid.txt')
    assert(pid_dict == sampled_census_dict)

def test_parse_census_place_id_lines():
    pid_dict = parse_census_place_id_lines(pid_test_list)
    assert(pid_dict == pid_list_dict)

def test_parse_census_place_id_line():
    pid_dict = parse_census_place_id_line(pid_test_list[0])
    assert(pid_dict == alabama_state_dict)

    pid_dict = parse_census_place_id_line(pid_test_list[1])
    assert(pid_dict == baldwin_county_dict)

